name: fitness_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  intl_utils: null
  flutter_localization: ^0.3.1
  flutter_launcher_icons: ^0.14.3
  glass_kit: ^4.0.1
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.17
  flutter_screenutil:
  awesome_snackbar_content:
  cached_network_image:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/super_fitness.png"
  adaptive_icon_background: "assets/icons/super_fitness.png"
  adaptive_icon_foreground: "assets/icons/super_fitness.png"

flutter_intl:
  enabled: true
