name: Flutter Tests

on:
  push:
    branches:
      - master # تشغيل الاختبارات عند push إلى فرع main
  pull_request:
    branches:
      - master # تشغيل الاختبارات عند إنشاء pull request إلى فرع main

jobs:
  test:
    runs-on: ubuntu-latest # استخدام نظام تشغيل Ubuntu

    steps:
      # 1. تحقق من الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. تحقق من الكود
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # Use the Eclipse Temurin distribution
          java-version: "17"

      # 2. إعداد Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # استخدام قناة Flutter المستقرة

      # 3. الحصول على التبعيات
      - name: Get dependencies
        run: flutter pub get

      # 4. تشغيل الاختبارات
      - name: Run tests
        run: flutter test

      # 5. (اختياري) بناء المشروع للتأكد من عدم وجود أخطاء
      - name: Build project
        run: flutter build apk --release

      # 6. (اختياري) تحميل Apk
      - name: Upload Apk
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk
